USE [master]
GO

/****** Object:  Database [NewTournament]    Script Date: 4/28/2025 12:00:24 AM ******/
CREATE DATABASE [NewTournament]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tournament', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\NewTournament.mdf' , SIZE = 16384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tournament_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\NewTournament_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewTournament].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewTournament] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewTournament] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewTournament] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewTournament] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewTournament] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewTournament] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [NewTournament] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewTournament] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewTournament] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewTournament] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewTournament] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewTournament] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewTournament] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewTournament] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewTournament] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NewTournament] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewTournament] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewTournament] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewTournament] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewTournament] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewTournament] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NewTournament] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewTournament] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NewTournament] SET  MULTI_USER 
GO

ALTER DATABASE [NewTournament] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewTournament] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewTournament] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewTournament] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NewTournament] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewTournament] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NewTournament] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NewTournament] SET  READ_WRITE 
GO


